version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "daily"
    registries:
      - jfrog-artifactroy

registries:
  jfrog-artifactroy:
    type: "npm-registry"
    url: "https://registry.npmjs.org"
    token: "${{secrets.EMPTY_TOKEN}}"
    replaces-base: true
